# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "precise32"
  config.vm.box_url = "http://files.vagrantup.com/precise32.box"
  config.vm.provision "chef_solo" do |chef|
    chef.add_recipe "cookbook0"
    chef.add_recipe "cookbook0::recipe0"
    # Sets default values for attributes.
    # Attributes are visible on the recipes as: `node[:cookbook0][:a]`
    chef.json = {
      "cookbook0" => {
        "override" => "d"
      }
    }
    chef.arguments = '-l debug'
  end
end
