#!/usr/bin/env bash

# one-liner boxes from command line!

# yes/no question
if zenity --question --text="Please press a button."; then
    zenity --info --text="You pressed Yes\!"
else
    zenity --error --text="You pressed No\!"
fi

# warning yes/no
zenity --warning --text "This will kill, are you sure?";echo $

# error ok to continue
zenity --error --text "Installation failed! "

# text input prompt
szAnswer=$(zenity --entry --text "where are you?" --entry-text "at home"); echo $szAnswer

# multiple fields table text input
zenity --list --text "Fill every row, and mark all rows before hitting 'OK'" --column "title" --print-column=2 --multiple --column "value" --editable "name" "(please override)" "host" "" "ip" ""

# info dialog (show some text only)
zenity --info --text "Join us at irc.freenode.net #lbe."

# show text box
gksudo lsof | zenity --text-info --width 530

# show list to user
find . --name "*.jpg" --or --name "*.png" |zenity --list --column "Pictures"

# radio list
ans=$(zenity  --list  --text "Is linux.byexamples.com helpful?" --radiolist  --column "Pick" --column "Opinion" TRUE Amazing FALSE Average FALSE "Difficult to follow" FALSE "Not helpful"); echo $ans

# check list
ans=$(zenity  --list  --text "How linux.byexamples can be improved?" --checklist  --column "Pick" --column "options" TRUE "More pictures" TRUE "More complete post" FALSE "Includes Installation guidelines" FALSE "Create a forum for question queries" --separator=":"); echo $ans

# file selection
szSavePath=$(zenity --file-selection --save --confirm-overwrite);echo $szSavePath

# progress dialog
gksudo lsof | tee >(zenity --progress --pulsate) >lsof.txt

# scale dialog
ans=$(zenity --scale --text "pick a number" --min-value=2 --max-value=100 --value=2 --step 2);echo $ans
