# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "precise32"
  config.vm.box_url = "http://files.vagrantup.com/precise32.box"
  config.vm.provision "chef_solo" do |chef|
    chef.add_recipe "cookbook0"
    chef.add_recipe "cookbook0::recipe0"
    chef.json = {
      "cookbook0" => {
        "override" => "d"
      }
    }
  end
end
