#make uses `$SHELL` var (makefile var) to determine the interpreter to use

#remember:

#- each rule line means one separated shell invocation
#- lines ending in `\`  get following line appended and are passed together to the interpreter
	#**with** the `\`

#default: sh

SHELL := /usr/bin/python

0:
	print 1

1:
	#a = 1
	#print a
