#whatever its name, the first rule is the default if no args
#
#however, `all` is a very standard name whith you should use
first:
	@echo first

#depends first call `depended` and `depened2`
depends: depended depended2
	@echo depends

depended:
	@echo depended

depended2:
	@echo depended2
