.POSIX:

## include

# Copy paste given file here.

# Both rules and definitions can be included.

# Sources another makefile here like shell `.` (dot)

include a.makefile
include b.makefile

# If the file does not exist, generate an error:

#include idontexist

# Ignore the error if the file does not exist:

-include idontexist-but-you-ignore-me
